# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IndiaGeocoder
                                 A QGIS plugin
 This plugin is used for analysis of HMIS data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-20
        copyright            : (C) 2018 by IIRS
        email                : kotishiva@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IndiaGeocoder class from file IndiaGeocoder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .india_geocoder import IndiaGeocoder
    return IndiaGeocoder(iface)
